################################################################ auth-svc

@auth_svc_base_url = http://localhost:{{APP_PORT}}

# @env-json-key AUTH_TOKEN access_token
POST {{auth_svc_base_url}}/auth/login
Authorization: Basic {{MYSQL_TEST_USERNAME}} {{MYSQL_TEST_PASSWORD}}
Content-Type: application/json

###

POST {{auth_svc_base_url}}/auth/validate
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json



################################################################ gateway-svc

@gateway_svc_base_url = http://localhost:8080

POST {{gateway_svc_base_url}}/login
Authorization: Basic {{MYSQL_TEST_USERNAME}} {{MYSQL_TEST_PASSWORD}}
Content-Type: application/json

###

# @file-to-variable LOGO_FILE_VAR ./../../logo.png binary
POST {{gateway_svc_base_url}}/upload
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{$timestamp}}
------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/jpeg
{{LOGO_FILE_VAR}}
------WebKitFormBoundary{{$timestamp}}--
