name: micro-arch
services:
  auth-svc:
    build:
      context: ./auth-svc
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 5004:5004
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  gateway-svc:
    build:
      context: ./gateway-svc
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_started
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - AUTH_SVC_ADDRESS=${AUTH_SVC_ADDRESS}
      - MONGO_URI=${MONGO_URI}
  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./auth-svc/volumes/mysql/:/var/lib/mysql
      - ./auth-svc/mysql-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./rabbit/volumes/rabbit/:/var/lib/rabbitmq
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
