@base = http://localhost:5000

# @env-json-key AUTH_TOKEN access_token
POST {{base}}/auth/login
Authorization: Basic {{USERNAME}} {{PASSWORD}}
Content-Type: application/json

###

POST {{base}}/auth/validate
Authorization: Bearer {{AUTH_TOKEN}}
Content-Type: application/json
