version: '3'
services:
  auth-svc:
    image: auth-svc
    ports:
      - 5000:5000
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./volumes/mysql/:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
