# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  # https://github.com/kubernetes/minikube/issues/8439
  # It seems currently in mac arm host.minikube.internal is not resolved inside the pod
  # DATABASE_URL: mysql://auth_user:auth_pass@host.minikube.internal:3306/auth
  DATABASE_URL: mysql://auth_user:auth_pass@192.168.65.2:3306/auth
  JWT_SECRET: mysecretjwt
---
