# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  PLACEHOLDER: "NONE"
---

